### ISSUE TITLE
Private link requirement

### ISSUE THREAD

**Issue by PowerShellCrack** [Azure/avdaccelerator#299]
If deploying the AVD accelerator; during the Network Connectivity page, it says it is recommended to setup an Azure Private DNS zone. If yes is selected, there is a drop down that says **Key vault**, yet it tries to connect to a **private link resource**. Naming isn't the issue; the issue is if the environment doesn't have a private link already create it won't allow it to create one for me. Yet if I create one prior, I have to build a vnet first and then I can build one, but yet I want it to connect to the new network created by this accelerator and in the same resource group.

It seems there is a lot of extra work after deploying to move it. **Would it be better to make the template create a private link during deployment if a existing network is selected or disable the option if creating a new network?**. Or maybe state that in the readme on how to do it prior?

![image](https://user-images.githubusercontent.com/20599825/216707708-3cb253e3-6952-4349-a1ec-2f38b9e54f69.png)

**Comment by danycontre** [comment]
@PowerShellCrack Thanks for you feedback.

Some comments:
- Recommendation is to use private DNS zones for Azure files and key vault, because by default the deployment will create private endpoints for the PaaS services (key vault and storage account).
- We are working on updates as private DNS zones in Gov will have different FQDN.
- Connecting the deployment to existing private DNS zones is optional (Recommended), when using this option private DNS zones must already exist before the deployment as the deployment will create private endpoints but not private DNS zones.
- No need to pre-create private endpoints.

Will contact you to further discuss.

cc: @shawntmeyer
