### ISSUE TITLE
Azure Files does not get AD integrated after successful deployment of AVD Baseline via Azure portal.

### ISSUE THREAD

**Issue by kevinsul** [Azure/avdaccelerator#310]
have noticed is that when I deploy with FSLogix/AD DS, everything succeeds, but the actual Azure Files file share does not automatically integrate with my AD.  That is, FSLogix and everything is installed and configured correctly but the Azure files file share is not accessible.  If I go in and manually set up AD and also set up the proper share and NTFS permissions, everything starts to work correctly with the profiles.  Is that by deign?

**Comment by danycontre** [comment]
@kevinsul AVD LZA code for AAD DS or AD DS deploys FSLogix end to end, so no it is not by design.

Did you provide private DNS zones for Azure files and Azure keyvault during deployment? this is needed by the FSLogix setup to complete properly.

If you provided the private DNs zones during deployment, please check as follows:
- Connect (RDP from AVD session hosts, bastion, etc.) to management VM inside service objects resource group.
- Check the content of the following log file: C:\Windows\Temp\ManualDscStorageScriptsLog.log, this file contains the logs of the custom script extension used to join storage account to the domain and NTFS setup on FSLogix file share.

To further assist please share any error messages found in the log file.

**Comment by kevinsul** [comment]
Ah - I see this in that log:  

Exception             : Microsoft.PowerShell.Commands.WriteErrorException: **Multiple OrganizationalUnits were found 
                        matching the name 'Computers':**
                        CN=Computers,DC=gbblab,DC=com
                        OU=Computers,OU=1phciou1,DC=gbblab,DC=com
                        To disambiguate the OU you want to join the storage account to, use the 
                        OrganizationalUnitDistinguishedName parameter.

...so I guess the script gets confused when the target OU is an OU with a name that  shows up in more than one place in the AD domain...

**Comment by kevinsul** [comment]
[ManualDscStorageScriptsLog.log](https://github.com/Azure/avdaccelerator/files/10885766/ManualDscStorageScriptsLog.log)

**Comment by danycontre** [comment]
Thank you @kevinsul great finding, we will need to check the code.

If you deploy using custom OU path, does it succeed?
