### ISSUE TITLE
Issue: Storage join for ADDS

### ISSUE THREAD

**Issue by jensheerin** [Azure/avdaccelerator#431]
GUI deployment with ADDS join storage does not join with no errors in deployment from portal. 
1st deployment (today) failed with permission in log file. However, VM joins successfully with same domain join account and password in the same OU.
2nd deployment no error log in c:\windows\temp.

**Comment by danycontre** [comment]
@jensheerin thanks for reporting the issue.

Some questions/comments:

- When logs is not create is because the management VM wasn't able to connect to the storage account.
- If you deployed private endpoints, MGMT VM is usually unable to connect to the storage account because of network resolution scenarios, please make sure that the mgmt VM can resolve the storage account DNS record to the private IP of the storage account's private endpoint, by default any other access is disabled on the storage account.
- If DNs resolution is working properly please let us know to continue with additional troubleshooting steps.
