### ISSUE TITLE
Default prefix for zero trust Key Vault

### ISSUE THREAD

**Issue by JoshuaMcConnaughey** [Azure/avdaccelerator#470]
After multiple failures using the greenfield ARM template in the portal (workload/arm/deploy-baseline.json), I think I discovered an error in the default naming convention for the zero trust Key Vault resource:

### Naming convention as documented
According to resource-naming.md, the zero trust Key Vault should be named like this:

kv-zt-{deploymentPrefix}-{DeploymentEnvironment}-{AzureRegionAcronym}-{uniqueString}

Note the "kv-zt" prefix.

### Naming convention in ARM template code (broken)
However, in the [deploy-baseline.json ARM template](https://github.com/Azure/avdaccelerator/blob/9ecd609a555a6b907bb67bfa665c7567abf46680/workload/arm/deploy-baseline.json), the prefix is set by default to "kv-key". This results in a name length violation if using a 4 character custom prefix and a 4 character environment (e.g. prod). In this case, the number of characters sums to 25, which is one longer than allowed for a key vault name.

### Relevant code section shown below:

`    "ztKvPrefixCustomName": {
      "type": "string",
      "defaultValue": "kv-key",
      "metadata": {
        "description": "AVD key vault custom name for zero trust and store store disk encryption key (Default: kv-key)"
      },
      "maxLength": 6
    },`

### Suggestion for corrected code:

`    "ztKvPrefixCustomName": {
      "type": "string",
      "defaultValue": "kv-zt",
      "metadata": {
        "description": "AVD key vault custom name for zero trust and store store disk encryption key (Default: kv-zt)"
      },
      "maxLength": 6
    },`

**Comment by danycontre** [comment]
@JoshuaMcConnaughey thanks for reporting the issues, we pushed updates to lower the unique string from 3 to 2 ramdom characters.

Please try your deployment again and let us know the outcome.

**Comment by danycontre** [comment]
@JoshuaMcConnaughey thanks for the heads up.

We just updated the diagrams and the naming md, so they are all aligned with the new naming.

Just to give you some background on the naming, kv-zt used to be the previous naming but we got feedback on naming be confusing since we were creating two key vaults, therefore key vaults were renamed to kv-sec (credentials secrets) and kv-key (disk encryption keys), a description tag was also added to the key vaults to make it easier to identify the purpose of each one.

Please let us know your feedback, happy to discuss further.
