### ISSUE TITLE
Groups and VNET lists not populating

### ISSUE THREAD

**Issue by j-d-harvey** [Azure/avdaccelerator#660]
### What happened? Provide a clear and concise description of the bug, including deployment details.

Trying to help a customer deploy the Landing Zone Accelerator but two different users with Owner permissions are seeing the same issue - on Identity tab the Groups drop down list does not populate and on the Networking tab the Azure Virtual Desktop virtual network list does not populate. Any idea how to solve this?

### Please provide the correlation id associated with your error or bug.

xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

### What was the expected outcome?

Lists populate

**Comment by danycontre** [comment]
@j-d-harvey thanks for your feedback.

Some comments:
- Existing vNet information not populating in the Networking tab dropdown:
- - A fix was pushed yesterday to enable selecting an existing vNet when not deploying session hosts.
- - The information in the drop down if filtered by:
- - - Subscription selected in deployment basics tab (doesn't apply to hub peering vNet, this one could be in any sub the user has access to).
- - - Region selected in the session hosts tab, or on the deployment basics tab if no session hosts are being deployed.
- Group drop down, this information is gathered using user's context Entra ID access, if it isn't populated is because the user has no rights to query identities in the tenant.
- - Test providing group details (name and ObjectID): 
![image](https://github.com/user-attachments/assets/340c80e3-7c9d-46ff-ad35-9c14fe569f08)

**Comment by j-d-harvey** [comment]
VNET populated this time. User is Global Admin but Group list still did not populate. However, specifying the name and Object Id did.
